<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StateCitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $states = [
            ['id' => 1, 'state_name' => 'Andhra Pradesh'],
            ['id' => 2, 'state_name' => 'Bihar'],
            ['id' => 3, 'state_name' => 'Chandigarh'],
            ['id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 5, 'state_name' => 'Delhi'],
            ['id' => 6, 'state_name' => 'Goa'],
            ['id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 8, 'state_name' => 'Haryana'],
            ['id' => 9, 'state_name' => 'Himachal Pradesh'],
            ['id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 13, 'state_name' => 'Kerala'],
            ['id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 16, 'state_name' => 'Punjab'],
            ['id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 18, 'state_name' => 'Sikkim'],
            ['id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 20, 'state_name' => 'Telangana'],
            ['id' => 21, 'state_name' => 'Tripura'],
            ['id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 23, 'state_name' => 'Uttarakhand'],
            ['id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 25, 'state_name' => 'Odisha'],
        ];

        $cities = [
            ['id' => 4, 'city_name' => 'Anantapur', 'state_id' => 1, 'state_name' => 'Andhra Pradesh'],
            ['id' => 5, 'city_name' => 'Chittoor', 'state_id' => 1, 'state_name' => 'Andhra Pradesh'],
            ['id' => 6, 'city_name' => 'Cuddapah', 'state_id' => 1, 'state_name' => 'Andhra Pradesh'],
            ['id' => 7, 'city_name' => 'East Godavari', 'state_id' => 1, 'state_name' => 'Andhra Pradesh'],
            ['id' => 8, 'city_name' => 'Guntur', 'state_id' => 1, 'state_name' => 'Andhra Pradesh'],
            ['id' => 9, 'city_name' => 'Krishna', 'state_id' => 1, 'state_name' => 'Andhra Pradesh'],
            ['id' => 10, 'city_name' => 'Kurnool', 'state_id' => 1, 'state_name' => 'Andhra Pradesh'],
            ['id' => 11, 'city_name' => 'Nellore', 'state_id' => 1, 'state_name' => 'Andhra Pradesh'],
            ['id' => 12, 'city_name' => 'Prakasam', 'state_id' => 1, 'state_name' => 'Andhra Pradesh'],
            ['id' => 13, 'city_name' => 'Srikakulam', 'state_id' => 1, 'state_name' => 'Andhra Pradesh'],
            ['id' => 14, 'city_name' => 'Visakhapatnam', 'state_id' => 1, 'state_name' => 'Andhra Pradesh'],
            ['id' => 15, 'city_name' => 'Vizianagaram', 'state_id' => 1, 'state_name' => 'Andhra Pradesh'],
            ['id' => 16, 'city_name' => 'West Godavari', 'state_id' => 1, 'state_name' => 'Andhra Pradesh'],



            ['id' => 61, 'city_name' => 'Araria', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 62, 'city_name' => 'Arwal', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 63, 'city_name' => 'Aurangabad', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 64, 'city_name' => 'Banka', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 65, 'city_name' => 'Begusarai', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 66, 'city_name' => 'Bhagalpur', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 67, 'city_name' => 'Bhojpur', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 68, 'city_name' => 'Buxar', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 69, 'city_name' => 'Darbhanga', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 70, 'city_name' => 'East Champaran (Motihari)', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 71, 'city_name' => 'Gaya', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 72, 'city_name' => 'Gopalganj', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 73, 'city_name' => 'Jamui', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 74, 'city_name' => 'Jehanabad', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 75, 'city_name' => 'Kaimur (Bhabua)', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 76, 'city_name' => 'Katihar', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 77, 'city_name' => 'Khagaria', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 78, 'city_name' => 'Kishanganj', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 79, 'city_name' => 'Lakhisarai', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 80, 'city_name' => 'Madhepura', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 81, 'city_name' => 'Madhubani', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 82, 'city_name' => 'Munger (Monghyr)', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 83, 'city_name' => 'Muzaffarpur', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 84, 'city_name' => 'Nalanda', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 85, 'city_name' => 'Nawada', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 86, 'city_name' => 'Patna', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 87, 'city_name' => 'Purnia (Purnea)', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 88, 'city_name' => 'Rohtas', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 89, 'city_name' => 'Saharsa', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 90, 'city_name' => 'Samastipur', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 91, 'city_name' => 'Saran', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 92, 'city_name' => 'Sheikhpura', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 93, 'city_name' => 'Sheohar', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 94, 'city_name' => 'Sitamarhi', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 95, 'city_name' => 'Siwan', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 96, 'city_name' => 'Supaul', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 97, 'city_name' => 'Vaishali', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 98, 'city_name' => 'West Champaran', 'state_id' => 2, 'state_name' => 'Bihar'],
            ['id' => 99, 'city_name' => 'Chandigarh', 'state_id' => 3, 'state_name' => 'Chandigarh'],
            ['id' => 100, 'city_name' => 'Balod', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 101, 'city_name' => 'Baloda Bazar', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 102, 'city_name' => 'Balrampur', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 103, 'city_name' => 'Bastar', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 104, 'city_name' => 'Bemetara', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 105, 'city_name' => 'Bijapur', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 106, 'city_name' => 'Bilaspur', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 107, 'city_name' => 'Dantewada (South Bastar)', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 108, 'city_name' => 'Dhamtari', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 109, 'city_name' => 'Durg', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 110, 'city_name' => 'Gariaband', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 111, 'city_name' => 'Janjgir-Champa', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 112, 'city_name' => 'Jashpur', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 113, 'city_name' => 'Kabirdham (Kawardha)', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 114, 'city_name' => 'Kanker (North Bastar)', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 115, 'city_name' => 'Kondagaon', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 116, 'city_name' => 'Korba', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 117, 'city_name' => 'Korea (Koriya)', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 118, 'city_name' => 'Mahasamund', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 119, 'city_name' => 'Mungeli', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 120, 'city_name' => 'Narayanpur', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 121, 'city_name' => 'Raigarh', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 122, 'city_name' => 'Raipur', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 123, 'city_name' => 'Rajnandgaon', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 124, 'city_name' => 'Sukma', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 125, 'city_name' => 'Surajpur', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],
            ['id' => 126, 'city_name' => 'Surguja', 'state_id' => 4, 'state_name' => 'Chhattisgarh'],

            ['id' => 130, 'city_name' => 'Central Delhi', 'state_id' => 5, 'state_name' => 'Delhi'],
            ['id' => 131, 'city_name' => 'East Delhi', 'state_id' => 5, 'state_name' => 'Delhi'],
            ['id' => 132, 'city_name' => 'New Delhi', 'state_id' => 5, 'state_name' => 'Delhi'],
            ['id' => 133, 'city_name' => 'North Delhi', 'state_id' => 5, 'state_name' => 'Delhi'],
            ['id' => 134, 'city_name' => 'North East Delhi', 'state_id' => 5, 'state_name' => 'Delhi'],
            ['id' => 135, 'city_name' => 'North West Delhi', 'state_id' => 5, 'state_name' => 'Delhi'],
            ['id' => 136, 'city_name' => 'South Delhi', 'state_id' => 5, 'state_name' => 'Delhi'],
            ['id' => 137, 'city_name' => 'South West Delhi', 'state_id' => 5, 'state_name' => 'Delhi'],
            ['id' => 138, 'city_name' => 'West Delhi', 'state_id' => 5, 'state_name' => 'Delhi'],

            ['id' => 139, 'city_name' => 'North Goa', 'state_id' => 6, 'state_name' => 'Goa'],
            ['id' => 140, 'city_name' => 'South Goa', 'state_id' => 6, 'state_name' => 'Goa'],
            ['id' => 141, 'city_name' => 'Ahmedabad', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 142, 'city_name' => 'Amreli', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 143, 'city_name' => 'Anand', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 144, 'city_name' => 'Aravalli', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 145, 'city_name' => 'Banaskantha (Palanpur)', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 146, 'city_name' => 'Bharuch', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 147, 'city_name' => 'Bhavnagar', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 148, 'city_name' => 'Botad', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 149, 'city_name' => 'Chhota Udepur', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 150, 'city_name' => 'Dahod', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 151, 'city_name' => 'Dangs (Ahwa)', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 152, 'city_name' => 'Devbhoomi Dwarka', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 153, 'city_name' => 'Gandhinagar', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 154, 'city_name' => 'Gir Somnath', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 155, 'city_name' => 'Jamnagar', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 156, 'city_name' => 'Junagadh', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 157, 'city_name' => 'Kachchh', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 158, 'city_name' => 'Kheda (Nadiad)', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 159, 'city_name' => 'Mahisagar', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 160, 'city_name' => 'Mehsana', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 161, 'city_name' => 'Morbi', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 162, 'city_name' => 'Narmada (Rajpipla)', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 163, 'city_name' => 'Navsari', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 164, 'city_name' => 'Panchmahal (Godhra)', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 165, 'city_name' => 'Patan', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 166, 'city_name' => 'Porbandar', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 167, 'city_name' => 'Rajkot', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 168, 'city_name' => 'Sabarkantha (Himmatnagar)', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 169, 'city_name' => 'Surat', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 170, 'city_name' => 'Surendranagar', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 171, 'city_name' => 'Tapi (Vyara)', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 172, 'city_name' => 'Vadodara', 'state_id' => 7, 'state_name' => 'Gujarat'],
            ['id' => 173, 'city_name' => 'Valsad', 'state_id' => 7, 'state_name' => 'Gujarat'],



            ['id' => 175, 'city_name' => 'Bhiwani', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 176, 'city_name' => 'Faridabad', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 177, 'city_name' => 'Fatehabad', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 178, 'city_name' => 'Gurgaon', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 179, 'city_name' => 'Hisar', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 180, 'city_name' => 'Jhajjar', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 181, 'city_name' => 'Jind', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 182, 'city_name' => 'Kaithal', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 183, 'city_name' => 'Karnal', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 184, 'city_name' => 'Kurukshetra', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 185, 'city_name' => 'Mahendragarh', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 186, 'city_name' => 'Mewat', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 187, 'city_name' => 'Palwal', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 188, 'city_name' => 'Panchkula', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 189, 'city_name' => 'Panipat', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 190, 'city_name' => 'Rewari', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 191, 'city_name' => 'Rohtak', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 192, 'city_name' => 'Sirsa', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 193, 'city_name' => 'Sonipat', 'state_id' => 8, 'state_name' => 'Haryana'],
            ['id' => 194, 'city_name' => 'Yamunanagar', 'state_id' => 8, 'state_name' => 'Haryana'],

            ['id' => 195, 'city_name' => 'Bilaspur', 'state_id' => 9, 'state_name' => 'Himachal Pradesh'],
            ['id' => 196, 'city_name' => 'Chamba', 'state_id' => 9, 'state_name' => 'Himachal Pradesh'],
            ['id' => 197, 'city_name' => 'Hamirpur', 'state_id' => 9, 'state_name' => 'Himachal Pradesh'],
            ['id' => 198, 'city_name' => 'Kangra', 'state_id' => 9, 'state_name' => 'Himachal Pradesh'],
            ['id' => 199, 'city_name' => 'Kinnaur', 'state_id' => 9, 'state_name' => 'Himachal Pradesh'],
            ['id' => 200, 'city_name' => 'Kullu', 'state_id' => 9, 'state_name' => 'Himachal Pradesh'],
            ['id' => 201, 'city_name' => 'Lahaul & Spiti', 'state_id' => 9, 'state_name' => 'Himachal Pradesh'],
            ['id' => 202, 'city_name' => 'Mandi', 'state_id' => 9, 'state_name' => 'Himachal Pradesh'],
            ['id' => 203, 'city_name' => 'Shimla', 'state_id' => 9, 'state_name' => 'Himachal Pradesh'],
            ['id' => 204, 'city_name' => 'Sirmaur (Sirmour)', 'state_id' => 9, 'state_name' => 'Himachal Pradesh'],
            ['id' => 205, 'city_name' => 'Solan', 'state_id' => 9, 'state_name' => 'Himachal Pradesh'],
            ['id' => 206, 'city_name' => 'Una', 'state_id' => 9, 'state_name' => 'Himachal Pradesh'],

            ['id' => 207, 'city_name' => 'Anantnag', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 208, 'city_name' => 'Bandipora', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 209, 'city_name' => 'Baramulla', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 210, 'city_name' => 'Budgam', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 211, 'city_name' => 'Doda', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 212, 'city_name' => 'Ganderbal', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 213, 'city_name' => 'Jammu', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 214, 'city_name' => 'Kargil', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 215, 'city_name' => 'Kathua', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 216, 'city_name' => 'Kishtwar', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 217, 'city_name' => 'Kulgam', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 218, 'city_name' => 'Kupwara', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 219, 'city_name' => 'Leh', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 220, 'city_name' => 'Poonch', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 221, 'city_name' => 'Pulwama', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 222, 'city_name' => 'Rajouri', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 223, 'city_name' => 'Ramban', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 224, 'city_name' => 'Reasi', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 225, 'city_name' => 'Samba', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 226, 'city_name' => 'Shopian', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 227, 'city_name' => 'Srinagar', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 228, 'city_name' => 'Udhampur', 'state_id' => 10, 'state_name' => 'Jammu and Kashmir'],

            ['id' => 229, 'city_name' => 'Bokaro', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 230, 'city_name' => 'Chatra', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 231, 'city_name' => 'Deoghar', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 232, 'city_name' => 'Dhanbad', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 233, 'city_name' => 'Dumka', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 234, 'city_name' => 'East Singhbhum', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 235, 'city_name' => 'Garhwa', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 236, 'city_name' => 'Giridih', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 237, 'city_name' => 'Godda', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 238, 'city_name' => 'Gumla', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 239, 'city_name' => 'Hazaribag', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 240, 'city_name' => 'Jamtara', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 241, 'city_name' => 'Khunti', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 242, 'city_name' => 'Koderma', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 243, 'city_name' => 'Latehar', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 244, 'city_name' => 'Lohardaga', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 245, 'city_name' => 'Pakur', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 246, 'city_name' => 'Palamu', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 247, 'city_name' => 'Ramgarh', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 248, 'city_name' => 'Ranchi', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 249, 'city_name' => 'Sahibganj', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 250, 'city_name' => 'Seraikela-Kharsawan', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 251, 'city_name' => 'Simdega', 'state_id' => 11, 'state_name' => 'Jharkhand'],
            ['id' => 252, 'city_name' => 'West Singhbhum', 'state_id' => 11, 'state_name' => 'Jharkhand'],

            ['id' => 253, 'city_name' => 'Bagalkot', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 254, 'city_name' => 'Bangalore Rural', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 255, 'city_name' => 'Bangalore Urban', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 256, 'city_name' => 'Belgaum', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 257, 'city_name' => 'Bellary', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 258, 'city_name' => 'Bidar', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 259, 'city_name' => 'Bijapur', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 260, 'city_name' => 'Chamarajanagar', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 261, 'city_name' => 'Chickmagalur', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 262, 'city_name' => 'Chikballapur', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 263, 'city_name' => 'Chitradurga', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 264, 'city_name' => 'Dakshina Kannada', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 265, 'city_name' => 'Davangere', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 266, 'city_name' => 'Dharwad', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 267, 'city_name' => 'Gadag', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 268, 'city_name' => 'Gulbarga', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 269, 'city_name' => 'Hassan', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 270, 'city_name' => 'Haveri', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 271, 'city_name' => 'Kodagu', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 272, 'city_name' => 'Kolar', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 273, 'city_name' => 'Koppal', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 274, 'city_name' => 'Mandya', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 275, 'city_name' => 'Mysore', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 276, 'city_name' => 'Raichur', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 277, 'city_name' => 'Ramnagara', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 278, 'city_name' => 'Shimoga', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 279, 'city_name' => 'Tumkur', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 280, 'city_name' => 'Udupi', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 281, 'city_name' => 'Uttara Kannada (Karwar)', 'state_id' => 12, 'state_name' => 'Karnataka'],
            ['id' => 282, 'city_name' => 'Yadgir', 'state_id' => 12, 'state_name' => 'Karnataka'],

            ['id' => 283, 'city_name' => 'Alappuzha', 'state_id' => 13, 'state_name' => 'Kerala'],
            ['id' => 284, 'city_name' => 'Ernakulam', 'state_id' => 13, 'state_name' => 'Kerala'],
            ['id' => 285, 'city_name' => 'Idukki', 'state_id' => 13, 'state_name' => 'Kerala'],
            ['id' => 286, 'city_name' => 'Kannur', 'state_id' => 13, 'state_name' => 'Kerala'],
            ['id' => 287, 'city_name' => 'Kasaragod', 'state_id' => 13, 'state_name' => 'Kerala'],
            ['id' => 288, 'city_name' => 'Kollam', 'state_id' => 13, 'state_name' => 'Kerala'],
            ['id' => 289, 'city_name' => 'Kottayam', 'state_id' => 13, 'state_name' => 'Kerala'],
            ['id' => 290, 'city_name' => 'Kozhikode', 'state_id' => 13, 'state_name' => 'Kerala'],
            ['id' => 291, 'city_name' => 'Malappuram', 'state_id' => 13, 'state_name' => 'Kerala'],
            ['id' => 292, 'city_name' => 'Palakkad', 'state_id' => 13, 'state_name' => 'Kerala'],
            ['id' => 293, 'city_name' => 'Pathanamthitta', 'state_id' => 13, 'state_name' => 'Kerala'],
            ['id' => 294, 'city_name' => 'Thiruvananthapuram', 'state_id' => 13, 'state_name' => 'Kerala'],
            ['id' => 295, 'city_name' => 'Thrissur', 'state_id' => 13, 'state_name' => 'Kerala'],
            ['id' => 296, 'city_name' => 'Wayanad', 'state_id' => 13, 'state_name' => 'Kerala'],

            ['id' => 298, 'city_name' => 'Alirajpur', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 299, 'city_name' => 'Anuppur', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 300, 'city_name' => 'Ashoknagar', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 301, 'city_name' => 'Balaghat', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 302, 'city_name' => 'Barwani', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 303, 'city_name' => 'Betul', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 304, 'city_name' => 'Bhind', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 305, 'city_name' => 'Bhopal', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 306, 'city_name' => 'Burhanpur', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 307, 'city_name' => 'Chhatarpur', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 308, 'city_name' => 'Chhindwara', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 309, 'city_name' => 'Damoh', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 310, 'city_name' => 'Datia', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 311, 'city_name' => 'Dewas', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 312, 'city_name' => 'Dhar', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 313, 'city_name' => 'Dindori', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 314, 'city_name' => 'Guna', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 315, 'city_name' => 'Gwalior', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 316, 'city_name' => 'Harda', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 317, 'city_name' => 'Hoshangabad', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 318, 'city_name' => 'Indore', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 319, 'city_name' => 'Jabalpur', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 320, 'city_name' => 'Jhabua', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 321, 'city_name' => 'Katni', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 322, 'city_name' => 'Khandwa', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 323, 'city_name' => 'Khargone', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 324, 'city_name' => 'Mandla', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 325, 'city_name' => 'Mandsaur', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 326, 'city_name' => 'Morena', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 327, 'city_name' => 'Narsinghpur', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 328, 'city_name' => 'Neemuch', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 329, 'city_name' => 'Panna', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 330, 'city_name' => 'Raisen', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 331, 'city_name' => 'Rajgarh', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 332, 'city_name' => 'Ratlam', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 333, 'city_name' => 'Rewa', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 334, 'city_name' => 'Sagar', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 335, 'city_name' => 'Satna', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 336, 'city_name' => 'Sehore', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 337, 'city_name' => 'Seoni', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 338, 'city_name' => 'Shahdol', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 339, 'city_name' => 'Shajapur', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 340, 'city_name' => 'Sheopur', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 341, 'city_name' => 'Shivpuri', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 342, 'city_name' => 'Sidhi', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 343, 'city_name' => 'Singrauli', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 344, 'city_name' => 'Tikamgarh', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 345, 'city_name' => 'Ujjain', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 346, 'city_name' => 'Umaria', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],
            ['id' => 347, 'city_name' => 'Vidisha', 'state_id' => 14, 'state_name' => 'Madhya Pradesh'],

            ['id' => 348, 'city_name' => 'Ahmednagar', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 349, 'city_name' => 'Akola', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 350, 'city_name' => 'Amravati', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 351, 'city_name' => 'Aurangabad', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 352, 'city_name' => 'Beed', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 353, 'city_name' => 'Bhandara', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 354, 'city_name' => 'Buldhana', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 355, 'city_name' => 'Chandrapur', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 356, 'city_name' => 'Dhule', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 357, 'city_name' => 'Gadchiroli', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 358, 'city_name' => 'Gondia', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 359, 'city_name' => 'Hingoli', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 360, 'city_name' => 'Jalgaon', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 361, 'city_name' => 'Jalna', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 362, 'city_name' => 'Kolhapur', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 363, 'city_name' => 'Latur', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 364, 'city_name' => 'Mumbai City', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 365, 'city_name' => 'Mumbai Suburban', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 366, 'city_name' => 'Nagpur', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 367, 'city_name' => 'Nanded', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 368, 'city_name' => 'Nandurbar', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 369, 'city_name' => 'Nashik', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 370, 'city_name' => 'Osmanabad', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 371, 'city_name' => 'Parbhani', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 372, 'city_name' => 'Pune', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 373, 'city_name' => 'Raigad', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 374, 'city_name' => 'Ratnagiri', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 375, 'city_name' => 'Sangli', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 376, 'city_name' => 'Satara', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 377, 'city_name' => 'Sindhudurg', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 378, 'city_name' => 'Solapur', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 379, 'city_name' => 'Thane', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 380, 'city_name' => 'Wardha', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 381, 'city_name' => 'Washim', 'state_id' => 15, 'state_name' => 'Maharashtra'],
            ['id' => 382, 'city_name' => 'Yavatmal', 'state_id' => 15, 'state_name' => 'Maharashtra'],

            ['id' => 422, 'city_name' => 'Angul', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 423, 'city_name' => 'Balangir', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 424, 'city_name' => 'Balasore', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 425, 'city_name' => 'Bargarh', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 426, 'city_name' => 'Bhadrak', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 427, 'city_name' => 'Boudh', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 428, 'city_name' => 'Cuttack', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 429, 'city_name' => 'Deogarh', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 430, 'city_name' => 'Dhenkanal', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 431, 'city_name' => 'Gajapati', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 432, 'city_name' => 'Ganjam', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 433, 'city_name' => 'Jagatsinghapur', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 434, 'city_name' => 'Jajpur', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 435, 'city_name' => 'Jharsuguda', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 436, 'city_name' => 'Kalahandi', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 437, 'city_name' => 'Kandhamal', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 438, 'city_name' => 'Kendrapara', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 439, 'city_name' => 'Kendujhar (Keonjhar)', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 440, 'city_name' => 'Khordha', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 441, 'city_name' => 'Koraput', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 442, 'city_name' => 'Malkangiri', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 443, 'city_name' => 'Mayurbhanj', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 444, 'city_name' => 'Nabarangpur', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 445, 'city_name' => 'Nayagarh', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 446, 'city_name' => 'Nuapada', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 447, 'city_name' => 'Puri', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 448, 'city_name' => 'Rayagada', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 449, 'city_name' => 'Sambalpur', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 450, 'city_name' => 'Sonepur', 'state_id' => 25, 'state_name' => 'Odisha'],
            ['id' => 451, 'city_name' => 'Sundargarh', 'state_id' => 25, 'state_name' => 'Odisha'],

            ['id' => 456, 'city_name' => 'Amritsar', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 457, 'city_name' => 'Barnala', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 458, 'city_name' => 'Bathinda', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 459, 'city_name' => 'Faridkot', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 460, 'city_name' => 'Fatehgarh Sahib', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 461, 'city_name' => 'Fazilka', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 462, 'city_name' => 'Ferozepur', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 463, 'city_name' => 'Gurdaspur', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 464, 'city_name' => 'Hoshiarpur', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 465, 'city_name' => 'Jalandhar', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 466, 'city_name' => 'Kapurthala', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 467, 'city_name' => 'Ludhiana', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 468, 'city_name' => 'Mansa', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 469, 'city_name' => 'Moga', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 470, 'city_name' => 'Muktsar', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 471, 'city_name' => 'Nawanshahr', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 472, 'city_name' => 'Pathankot', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 473, 'city_name' => 'Patiala', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 474, 'city_name' => 'Rupnagar', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 475, 'city_name' => 'Sangrur', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 476, 'city_name' => 'SAS Nagar (Mohali)', 'state_id' => 16, 'state_name' => 'Punjab'],
            ['id' => 477, 'city_name' => 'Tarn Taran', 'state_id' => 16, 'state_name' => 'Punjab'],

            ['id' => 479, 'city_name' => 'Alwar', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 480, 'city_name' => 'Banswara', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 481, 'city_name' => 'Baran', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 482, 'city_name' => 'Barmer', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 483, 'city_name' => 'Bharatpur', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 484, 'city_name' => 'Bhilwara', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 485, 'city_name' => 'Bikaner', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 486, 'city_name' => 'Bundi', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 487, 'city_name' => 'Chittorgarh', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 488, 'city_name' => 'Churu', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 489, 'city_name' => 'Dausa', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 490, 'city_name' => 'Dholpur', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 491, 'city_name' => 'Dungarpur', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 492, 'city_name' => 'Hanumangarh', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 493, 'city_name' => 'Jaipur', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 494, 'city_name' => 'Jaisalmer', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 495, 'city_name' => 'Jalore', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 496, 'city_name' => 'Jhalawar', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 497, 'city_name' => 'Jhunjhunu', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 498, 'city_name' => 'Jodhpur', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 499, 'city_name' => 'Karauli', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 500, 'city_name' => 'Kota', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 501, 'city_name' => 'Nagaur', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 502, 'city_name' => 'Pali', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 503, 'city_name' => 'Pratapgarh', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 504, 'city_name' => 'Rajsamand', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 505, 'city_name' => 'Sawai Madhopur', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 506, 'city_name' => 'Sikar', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 507, 'city_name' => 'Sirohi', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 508, 'city_name' => 'Sri Ganganagar', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 509, 'city_name' => 'Tonk', 'state_id' => 17, 'state_name' => 'Rajasthan'],
            ['id' => 510, 'city_name' => 'Udaipur', 'state_id' => 17, 'state_name' => 'Rajasthan'],

            ['id' => 511, 'city_name' => 'East Sikkim', 'state_id' => 18, 'state_name' => 'Sikkim'],
            ['id' => 512, 'city_name' => 'North Sikkim', 'state_id' => 18, 'state_name' => 'Sikkim'],
            ['id' => 513, 'city_name' => 'South Sikkim', 'state_id' => 18, 'state_name' => 'Sikkim'],
            ['id' => 514, 'city_name' => 'West Sikkim', 'state_id' => 18, 'state_name' => 'Sikkim'],

            ['id' => 515, 'city_name' => 'Ariyalur', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 516, 'city_name' => 'Chennai', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 517, 'city_name' => 'Coimbatore', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 518, 'city_name' => 'Cuddalore', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 519, 'city_name' => 'Dharmapuri', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 520, 'city_name' => 'Dindigul', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 521, 'city_name' => 'Erode', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 522, 'city_name' => 'Kanchipuram', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 523, 'city_name' => 'Kanyakumari', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 524, 'city_name' => 'Karur', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 525, 'city_name' => 'Krishnagiri', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 526, 'city_name' => 'Madurai', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 527, 'city_name' => 'Nagapattinam', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 528, 'city_name' => 'Namakkal', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 529, 'city_name' => 'Nilgiris', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 530, 'city_name' => 'Perambalur', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 531, 'city_name' => 'Pudukkottai', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 532, 'city_name' => 'Ramanathapuram', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 533, 'city_name' => 'Salem', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 534, 'city_name' => 'Sivaganga', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 535, 'city_name' => 'Thanjavur', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 536, 'city_name' => 'Theni', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 537, 'city_name' => 'Thoothukudi (Tuticorin)', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 538, 'city_name' => 'Tiruchirappalli', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 539, 'city_name' => 'Tirunelveli', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 540, 'city_name' => 'Tiruppur', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 541, 'city_name' => 'Tiruvallur', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 542, 'city_name' => 'Tiruvannamalai', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 543, 'city_name' => 'Tiruvarur', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 544, 'city_name' => 'Vellore', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 545, 'city_name' => 'Viluppuram', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],
            ['id' => 546, 'city_name' => 'Virudhunagar', 'state_id' => 19, 'state_name' => 'Tamil Nadu'],

            ['id' => 547, 'city_name' => 'Adilabad', 'state_id' => 20, 'state_name' => 'Telangana'],
            ['id' => 548, 'city_name' => 'Hyderabad', 'state_id' => 20, 'state_name' => 'Telangana'],
            ['id' => 549, 'city_name' => 'Karimnagar', 'state_id' => 20, 'state_name' => 'Telangana'],
            ['id' => 550, 'city_name' => 'Khammam', 'state_id' => 20, 'state_name' => 'Telangana'],
            ['id' => 551, 'city_name' => 'Mahabubnagar', 'state_id' => 20, 'state_name' => 'Telangana'],
            ['id' => 552, 'city_name' => 'Medak', 'state_id' => 20, 'state_name' => 'Telangana'],
            ['id' => 553, 'city_name' => 'Nalgonda', 'state_id' => 20, 'state_name' => 'Telangana'],
            ['id' => 554, 'city_name' => 'Nizamabad', 'state_id' => 20, 'state_name' => 'Telangana'],
            ['id' => 555, 'city_name' => 'Rangareddy', 'state_id' => 20, 'state_name' => 'Telangana'],
            ['id' => 556, 'city_name' => 'Warangal', 'state_id' => 20, 'state_name' => 'Telangana'],

            ['id' => 565, 'city_name' => 'Agra', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 566, 'city_name' => 'Aligarh', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 567, 'city_name' => 'Prayagraj', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 568, 'city_name' => 'Ambedkar Nagar', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 569, 'city_name' => 'Auraiya', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 570, 'city_name' => 'Azamgarh', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 571, 'city_name' => 'Baghpat', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 572, 'city_name' => 'Bahraich', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 573, 'city_name' => 'Ballia', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 574, 'city_name' => 'Balrampur', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 575, 'city_name' => 'Banda', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 576, 'city_name' => 'Barabanki', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 577, 'city_name' => 'Bareilly', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 578, 'city_name' => 'Basti', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 579, 'city_name' => 'Sambhal', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 580, 'city_name' => 'Bijnor', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 581, 'city_name' => 'Budaun', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 582, 'city_name' => 'Bulandshahr', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 583, 'city_name' => 'Chandauli', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 584, 'city_name' => 'Amethi', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 585, 'city_name' => 'Chitrakoot', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 586, 'city_name' => 'Deoria', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 587, 'city_name' => 'Etah', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 588, 'city_name' => 'Etawah', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 589, 'city_name' => 'Ayodhya', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 590, 'city_name' => 'Farrukhabad', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 591, 'city_name' => 'Fatehpur', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 592, 'city_name' => 'Firozabad', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 593, 'city_name' => 'Gautam Buddha Nagar', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 594, 'city_name' => 'Ghaziabad', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 595, 'city_name' => 'Ghazipur', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 596, 'city_name' => 'Gonda', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 597, 'city_name' => 'Gorakhpur', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 598, 'city_name' => 'Hamirpur', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 599, 'city_name' => 'Hardoi', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 600, 'city_name' => 'Hathras', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 601, 'city_name' => 'Jalaun', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 602, 'city_name' => 'Jaunpur', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 603, 'city_name' => 'Jhansi', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 604, 'city_name' => 'Amroha', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 605, 'city_name' => 'Kannauj', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 606, 'city_name' => 'Kanpur Dehat', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 607, 'city_name' => 'Kanpur Nagar', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 608, 'city_name' => 'Kasganj', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 609, 'city_name' => 'Kaushambi', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 610, 'city_name' => 'Kushinagar', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 611, 'city_name' => 'Lakhimpur Kheri', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 612, 'city_name' => 'Lalitpur', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 613, 'city_name' => 'Lucknow', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 614, 'city_name' => 'Maharajganj', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 615, 'city_name' => 'Mahoba', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 616, 'city_name' => 'Mainpuri', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 617, 'city_name' => 'Mathura', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 618, 'city_name' => 'Mau', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 619, 'city_name' => 'Meerut', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 620, 'city_name' => 'Mirzapur', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 621, 'city_name' => 'Moradabad', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 622, 'city_name' => 'Muzaffarnagar', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 623, 'city_name' => 'Hapur', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 624, 'city_name' => 'Pilibhit', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 625, 'city_name' => 'Shamli', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 626, 'city_name' => 'Pratapgarh', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 627, 'city_name' => 'Rae Bareli', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 628, 'city_name' => 'Rampur', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 629, 'city_name' => 'Saharanpur', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 630, 'city_name' => 'Sant Kabir Nagar', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 631, 'city_name' => 'Bhadohi', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 632, 'city_name' => 'Shahjahanpur', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 633, 'city_name' => 'Shravasti', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 634, 'city_name' => 'Siddharth Nagar', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 635, 'city_name' => 'Sitapur', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 636, 'city_name' => 'Sonbhadra', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 637, 'city_name' => 'Sultanpur', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 638, 'city_name' => 'Unnao', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],
            ['id' => 639, 'city_name' => 'Varanasi', 'state_id' => 22, 'state_name' => 'Uttar Pradesh'],

            ['id' => 640, 'city_name' => 'Almora', 'state_id' => 23, 'state_name' => 'Uttarakhand'],
            ['id' => 641, 'city_name' => 'Bageshwar', 'state_id' => 23, 'state_name' => 'Uttarakhand'],
            ['id' => 642, 'city_name' => 'Chamoli', 'state_id' => 23, 'state_name' => 'Uttarakhand'],
            ['id' => 643, 'city_name' => 'Champawat', 'state_id' => 23, 'state_name' => 'Uttarakhand'],
            ['id' => 644, 'city_name' => 'Dehradun', 'state_id' => 23, 'state_name' => 'Uttarakhand'],
            ['id' => 645, 'city_name' => 'Haridwar', 'state_id' => 23, 'state_name' => 'Uttarakhand'],
            ['id' => 646, 'city_name' => 'Nainital', 'state_id' => 23, 'state_name' => 'Uttarakhand'],
            ['id' => 647, 'city_name' => 'Pauri Garhwal', 'state_id' => 23, 'state_name' => 'Uttarakhand'],
            ['id' => 648, 'city_name' => 'Pithoragarh', 'state_id' => 23, 'state_name' => 'Uttarakhand'],
            ['id' => 649, 'city_name' => 'Rudraprayag', 'state_id' => 23, 'state_name' => 'Uttarakhand'],
            ['id' => 650, 'city_name' => 'Tehri Garhwal', 'state_id' => 23, 'state_name' => 'Uttarakhand'],
            ['id' => 651, 'city_name' => 'Udham Singh Nagar', 'state_id' => 23, 'state_name' => 'Uttarakhand'],
            ['id' => 652, 'city_name' => 'Uttarkashi', 'state_id' => 23, 'state_name' => 'Uttarakhand'],

            ['id' => 653, 'city_name' => 'Bankura', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 654, 'city_name' => 'Birbhum', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 655, 'city_name' => 'Burdwan (Bardhaman)', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 656, 'city_name' => 'Cooch Behar', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 657, 'city_name' => 'Dakshin Dinajpur (South Dinajpur)', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 658, 'city_name' => 'Darjeeling', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 659, 'city_name' => 'Hooghly', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 660, 'city_name' => 'Howrah', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 661, 'city_name' => 'Jalpaiguri', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 662, 'city_name' => 'Kolkata', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 663, 'city_name' => 'Malda', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 664, 'city_name' => 'Murshidabad', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 665, 'city_name' => 'Nadia', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 666, 'city_name' => 'North 24 Parganas', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 667, 'city_name' => 'Paschim Medinipur (West Medinipur)', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 668, 'city_name' => 'Purba Medinipur (East Medinipur)', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 669, 'city_name' => 'Purulia', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 670, 'city_name' => 'South 24 Parganas', 'state_id' => 24, 'state_name' => 'West Bengal'],
            ['id' => 671, 'city_name' => 'Uttar Dinajpur (North Dinajpur)', 'state_id' => 24, 'state_name' => 'West Bengal']
        ];

        DB::table('cities')->truncate();
        DB::table('states')->truncate();

        DB::table('states')->insert($states);
        DB::table('cities')->insert($cities);
    }
}
