<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StateCitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $states = [
            ['id' => 1, 'state_name' => 'Andaman and Nicobar Island'],
            ['id' => 2, 'state_name' => 'Andhra Pradesh'],
            ['id' => 3, 'state_name' => 'Arunachal Pradesh'],
            ['id' => 4, 'state_name' => 'Assam'],
            ['id' => 5, 'state_name' => 'Bihar'],
            ['id' => 6, 'state_name' => 'Chandigarh'],
            ['id' => 7, 'state_name' => 'Chhattisgarh'],
            ['id' => 8, 'state_name' => 'Dadra and Nagar Haveli'],
            ['id' => 9, 'state_name' => 'Daman and Diu'],
            ['id' => 10, 'state_name' => 'Delhi'],
            ['id' => 11, 'state_name' => 'Goa'],
            ['id' => 12, 'state_name' => 'Gujarat'],
            ['id' => 13, 'state_name' => 'Haryana'],
            ['id' => 14, 'state_name' => 'Himachal Pradesh'],
            ['id' => 15, 'state_name' => 'Jammu and Kashmir'],
            ['id' => 16, 'state_name' => 'Jharkhand'],
            ['id' => 17, 'state_name' => 'Karnataka'],
            ['id' => 18, 'state_name' => 'Kerala'],
            ['id' => 19, 'state_name' => 'Lakshadweep'],
            ['id' => 20, 'state_name' => 'Madhya Pradesh'],
            ['id' => 21, 'state_name' => 'Maharashtra'],
            ['id' => 22, 'state_name' => 'Manipur'],
            ['id' => 23, 'state_name' => 'Meghalaya'],
            ['id' => 24, 'state_name' => 'Mizoram'],
            ['id' => 25, 'state_name' => 'Nagaland'],
            ['id' => 26, 'state_name' => 'Odisha'],
            ['id' => 27, 'state_name' => 'Puducherry'],
            ['id' => 28, 'state_name' => 'Punjab'],
            ['id' => 29, 'state_name' => 'Rajasthan'],
            ['id' => 30, 'state_name' => 'Sikkim'],
            ['id' => 31, 'state_name' => 'Tamil Nadu'],
            ['id' => 32, 'state_name' => 'Telangana'],
            ['id' => 33, 'state_name' => 'Tripura'],
            ['id' => 34, 'state_name' => 'Uttar Pradesh'],
            ['id' => 35, 'state_name' => 'Uttarakhand'],
            ['id' => 36, 'state_name' => 'West Bengal']
        ];

$cities = [['id'=>1,'city_name'=>'Nicobar', 'state_id' => 1, 'state_name' => 'Andaman and Nicobar Island'],
    ['id'=>2,'city_name'=>'North and Middle Andaman', 'state_id' => 1, 'state_name' => 'Andaman and Nicobar Island'],
    ['id'=>3,'city_name'=>'South Andaman', 'state_id' => 1, 'state_name' => 'Andaman and Nicobar Island'],
    ['id'=>4,'city_name'=>'Anantapur', 'state_id' => 2, 'state_name' => 'Andhra Pradesh'],
    ['id'=>5,'city_name'=>'Chittoor', 'state_id' => 2, 'state_name' => 'Andhra Pradesh'],
    ['id'=>6,'city_name'=>'Cuddapah', 'state_id' => 2, 'state_name' => 'Andhra Pradesh'],
    ['id'=>7,'city_name'=>'East Godavari', 'state_id' => 2, 'state_name' => 'Andhra Pradesh'],
    ['id'=>8,'city_name'=>'Guntur', 'state_id' => 2, 'state_name' => 'Andhra Pradesh'],
    ['id'=>9,'city_name'=>'Krishna', 'state_id' => 2, 'state_name' => 'Andhra Pradesh'],
    ['id'=>10,'city_name'=>'Kurnool', 'state_id' => 2, 'state_name' => 'Andhra Pradesh'],
    ['id'=>11,'city_name'=>'Nellore', 'state_id' => 2, 'state_name' => 'Andhra Pradesh'],
    ['id'=>12,'city_name'=>'Prakasam', 'state_id' => 2, 'state_name' => 'Andhra Pradesh'],
    ['id'=>13,'city_name'=>'Srikakulam', 'state_id' => 2, 'state_name' => 'Andhra Pradesh'],
    ['id'=>14,'city_name'=>'Visakhapatnam', 'state_id' => 2, 'state_name' => 'Andhra Pradesh'],
    ['id'=>15,'city_name'=>'Vizianagaram', 'state_id' => 2, 'state_name' => 'Andhra Pradesh'],
    ['id'=>16,'city_name'=>'West Godavari', 'state_id' => 2, 'state_name' => 'Andhra Pradesh'],
    ['id'=>17,'city_name'=>'Anjaw', 'state_id' => 3, 'state_name' => 'Arunachal Pradesh'],
    ['id'=>18,'city_name'=>'Changlang', 'state_id' => 3, 'state_name' => 'Arunachal Pradesh'],
    ['id'=>19,'city_name'=>'Dibang Valley', 'state_id' => 3, 'state_name' => 'Arunachal Pradesh'],
    ['id'=>20,'city_name'=>'East Kameng', 'state_id' => 3, 'state_name' => 'Arunachal Pradesh'],
    ['id'=>21,'city_name'=>'East Siang', 'state_id' => 3, 'state_name' => 'Arunachal Pradesh'],
    ['id'=>22,'city_name'=>'Kurung Kumey', 'state_id' => 3, 'state_name' => 'Arunachal Pradesh'],
    ['id'=>23,'city_name'=>'Lohit', 'state_id' => 3, 'state_name' => 'Arunachal Pradesh'],
    ['id'=>24,'city_name'=>'Longding', 'state_id' => 3, 'state_name' => 'Arunachal Pradesh'],
    ['id'=>25,'city_name'=>'Lower Dibang Valley', 'state_id' => 3, 'state_name' => 'Arunachal Pradesh'],
    ['id'=>26,'city_name'=>'Lower Subansiri', 'state_id' => 3, 'state_name' => 'Arunachal Pradesh'],
    ['id'=>27,'city_name'=>'Papum Pare', 'state_id' => 3, 'state_name' => 'Arunachal Pradesh'],
    ['id'=>28,'city_name'=>'Tawang', 'state_id' => 3, 'state_name' => 'Arunachal Pradesh'],
    ['id'=>29,'city_name'=>'Tirap', 'state_id' => 3, 'state_name' => 'Arunachal Pradesh'],
    ['id'=>30,'city_name'=>'Upper Siang', 'state_id' => 3, 'state_name' => 'Arunachal Pradesh'],
    ['id'=>31,'city_name'=>'Upper Subansiri', 'state_id' => 3, 'state_name' => 'Arunachal Pradesh'],
    ['id'=>32,'city_name'=>'West Kameng', 'state_id' => 3, 'state_name' => 'Arunachal Pradesh'],
    ['id'=>33,'city_name'=>'West Siang', 'state_id' => 3, 'state_name' => 'Arunachal Pradesh'],
    ['id'=>34,'city_name'=>'Baksa', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>35,'city_name'=>'Barpeta', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>36,'city_name'=>'Bongaigaon', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>37,'city_name'=>'Cachar', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>38,'city_name'=>'Chirang', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>39,'city_name'=>'Darrang', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>40,'city_name'=>'Dhemaji', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>41,'city_name'=>'Dhubri', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>42,'city_name'=>'Dibrugarh', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>43,'city_name'=>'Dima Hasao', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>44,'city_name'=>'Goalpara', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>45,'city_name'=>'Golaghat', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>46,'city_name'=>'Hailakandi', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>47,'city_name'=>'Jorhat', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>48,'city_name'=>'Kamrup Metropolitan', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>49,'city_name'=>'Kamrup', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>50,'city_name'=>'Karbi Anglong', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>51,'city_name'=>'Karimganj', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>52,'city_name'=>'Kokrajhar', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>53,'city_name'=>'Lakhimpur', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>54,'city_name'=>'Morigaon', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>55,'city_name'=>'Nagaon', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>56,'city_name'=>'Nalbari', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>57,'city_name'=>'Sivasagar', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>58,'city_name'=>'Sonitpur', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>59,'city_name'=>'Tinsukia', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>60,'city_name'=>'Udalguri', 'state_id' => 4, 'state_name' => 'Assam'],
    ['id'=>61,'city_name'=>'Araria', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>62,'city_name'=>'Arwal', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>63,'city_name'=>'Aurangabad', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>64,'city_name'=>'Banka', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>65,'city_name'=>'Begusarai', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>66,'city_name'=>'Bhagalpur', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>67,'city_name'=>'Bhojpur', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>68,'city_name'=>'Buxar', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>69,'city_name'=>'Darbhanga', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>70,'city_name'=>'East Champaran (Motihari)', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>71,'city_name'=>'Gaya', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>72,'city_name'=>'Gopalganj', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>73,'city_name'=>'Jamui', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>74,'city_name'=>'Jehanabad', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>75,'city_name'=>'Kaimur (Bhabua)', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>76,'city_name'=>'Katihar', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>77,'city_name'=>'Khagaria', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>78,'city_name'=>'Kishanganj', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>79,'city_name'=>'Lakhisarai', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>80,'city_name'=>'Madhepura', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>81,'city_name'=>'Madhubani', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>82,'city_name'=>'Munger (Monghyr)', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>83,'city_name'=>'Muzaffarpur', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>84,'city_name'=>'Nalanda', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>85,'city_name'=>'Nawada', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>86,'city_name'=>'Patna', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>87,'city_name'=>'Purnia (Purnea)', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>88,'city_name'=>'Rohtas', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>89,'city_name'=>'Saharsa', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>90,'city_name'=>'Samastipur', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>91,'city_name'=>'Saran', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>92,'city_name'=>'Sheikhpura', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>93,'city_name'=>'Sheohar', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>94,'city_name'=>'Sitamarhi', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>95,'city_name'=>'Siwan', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>96,'city_name'=>'Supaul', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>97,'city_name'=>'Vaishali', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>98,'city_name'=>'West Champaran', 'state_id' => 5, 'state_name' => 'Bihar'],
    ['id'=>99,'city_name'=>'Chandigarh', 'state_id' => 6, 'state_name' => 'Chandigarh'],
    ['id'=>100,'city_name'=>'Balod', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>101,'city_name'=>'Baloda Bazar', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>102,'city_name'=>'Balrampur', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>103,'city_name'=>'Bastar', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>104,'city_name'=>'Bemetara', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>105,'city_name'=>'Bijapur', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>106,'city_name'=>'Bilaspur', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>107,'city_name'=>'Dantewada (South Bastar)', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>108,'city_name'=>'Dhamtari', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>109,'city_name'=>'Durg', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>110,'city_name'=>'Gariaband', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>111,'city_name'=>'Janjgir-Champa', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>112,'city_name'=>'Jashpur', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>113,'city_name'=>'Kabirdham (Kawardha)', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>114,'city_name'=>'Kanker (North Bastar)', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>115,'city_name'=>'Kondagaon', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>116,'city_name'=>'Korba', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>117,'city_name'=>'Korea (Koriya)', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>118,'city_name'=>'Mahasamund', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>119,'city_name'=>'Mungeli', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>120,'city_name'=>'Narayanpur', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>121,'city_name'=>'Raigarh', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>122,'city_name'=>'Raipur', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>123,'city_name'=>'Rajnandgaon', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>124,'city_name'=>'Sukma', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>125,'city_name'=>'Surajpur', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>126,'city_name'=>'Surguja', 'state_id' => 7, 'state_name' => 'Chhattisgarh'],
    ['id'=>127,'city_name'=>'Dadra & Nagar Haveli', 'state_id' => 8, 'state_name' => 'Dadra and Nagar Haveli'],
    ['id'=>128,'city_name'=>'Daman', 'state_id' => 9, 'state_name' => 'Daman and Diu'],
    ['id'=>129,'city_name'=>'Diu', 'state_id' => 9, 'state_name' => 'Daman and Diu'],
    ['id'=>130,'city_name'=>'Central Delhi', 1'state_id' => 0, 'state_name' => 'Delhi'],
    ['id'=>131,'city_name'=>'East Delhi', 1'state_id' => 0, 'state_name' => 'Delhi'],
    ['id'=>132,'city_name'=>'New Delhi', 1'state_id' => 0, 'state_name' => 'Delhi'],
    ['id'=>133,'city_name'=>'North Delhi', 1'state_id' => 0, 'state_name' => 'Delhi'],
    ['id'=>134,'city_name'=>'North East Delhi', 1'state_id' => 0, 'state_name' => 'Delhi'],
    ['id'=>135,'city_name'=>'North West Delhi', 1'state_id' => 0, 'state_name' => 'Delhi'],
    ['id'=>136,'city_name'=>'South Delhi', 1'state_id' => 0, 'state_name' => 'Delhi'],
    ['id'=>137,'city_name'=>'South West Delhi', 1'state_id' => 0, 'state_name' => 'Delhi'],
    ['id'=>138,'city_name'=>'West Delhi', 1'state_id' => 0, 'state_name' => 'Delhi'],
    ['id'=>139,'city_name'=>'North Goa', 1'state_id' => 1, 'state_name' => 'Goa'],
    ['id'=>140,'city_name'=>'South Goa', 1'state_id' => 1, 'state_name' => 'Goa'],
    ['id'=>141,'city_name'=>'Ahmedabad', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>142,'city_name'=>'Amreli', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>143,'city_name'=>'Anand', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>144,'city_name'=>'Aravalli', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>145,'city_name'=>'Banaskantha (Palanpur)', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>146,'city_name'=>'Bharuch', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>147,'city_name'=>'Bhavnagar', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>148,'city_name'=>'Botad', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>149,'city_name'=>'Chhota Udepur', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>150,'city_name'=>'Dahod', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>151,'city_name'=>'Dangs (Ahwa)', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>152,'city_name'=>'Devbhoomi Dwarka', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>153,'city_name'=>'Gandhinagar', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>154,'city_name'=>'Gir Somnath', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>155,'city_name'=>'Jamnagar', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>156,'city_name'=>'Junagadh', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>157,'city_name'=>'Kachchh', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>158,'city_name'=>'Kheda (Nadiad)', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>159,'city_name'=>'Mahisagar', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>160,'city_name'=>'Mehsana', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>161,'city_name'=>'Morbi', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>162,'city_name'=>'Narmada (Rajpipla)', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>163,'city_name'=>'Navsari', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>164,'city_name'=>'Panchmahal (Godhra)', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>165,'city_name'=>'Patan', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>166,'city_name'=>'Porbandar', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>167,'city_name'=>'Rajkot', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>168,'city_name'=>'Sabarkantha (Himmatnagar)', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>169,'city_name'=>'Surat', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>170,'city_name'=>'Surendranagar', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>171,'city_name'=>'Tapi (Vyara)', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>172,'city_name'=>'Vadodara', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>173,'city_name'=>'Valsad', 1'state_id' => 2, 'state_name' => 'Gujarat'],
    ['id'=>174,'city_name'=>'Ambala k', 'state_id' => 1, 'state_name' => 'NULL'],
    ['id'=>175,'city_name'=>'Bhiwani', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>176,'city_name'=>'Faridabad', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>177,'city_name'=>'Fatehabad', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>178,'city_name'=>'Gurgaon', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>179,'city_name'=>'Hisar', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>180,'city_name'=>'Jhajjar', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>181,'city_name'=>'Jind', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>182,'city_name'=>'Kaithal', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>183,'city_name'=>'Karnal', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>184,'city_name'=>'Kurukshetra', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>185,'city_name'=>'Mahendragarh', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>186,'city_name'=>'Mewat', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>187,'city_name'=>'Palwal', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>188,'city_name'=>'Panchkula', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>189,'city_name'=>'Panipat', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>190,'city_name'=>'Rewari', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>191,'city_name'=>'Rohtak', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>192,'city_name'=>'Sirsa', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>193,'city_name'=>'Sonipat', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>194,'city_name'=>'Yamunanagar', 1'state_id' => 3, 'state_name' => 'Haryana'],
    ['id'=>195,'city_name'=>'Bilaspur', 1'state_id' => 4, 'state_name' => 'Himachal Pradesh'],
    ['id'=>196,'city_name'=>'Chamba', 1'state_id' => 4, 'state_name' => 'Himachal Pradesh'],
    ['id'=>197,'city_name'=>'Hamirpur', 1'state_id' => 4, 'state_name' => 'Himachal Pradesh'],
    ['id'=>198,'city_name'=>'Kangra', 1'state_id' => 4, 'state_name' => 'Himachal Pradesh'],
    ['id'=>199,'city_name'=>'Kinnaur', 1'state_id' => 4, 'state_name' => 'Himachal Pradesh'],
    ['id'=>200,'city_name'=>'Kullu', 1'state_id' => 4, 'state_name' => 'Himachal Pradesh'],
    ['id'=>201,'city_name'=>'Lahaul & Spiti', 1'state_id' => 4, 'state_name' => 'Himachal Pradesh'],
    ['id'=>202,'city_name'=>'Mandi', 1'state_id' => 4, 'state_name' => 'Himachal Pradesh'],
    ['id'=>203,'city_name'=>'Shimla', 1'state_id' => 4, 'state_name' => 'Himachal Pradesh'],
    ['id'=>204,'city_name'=>'Sirmaur (Sirmour)', 1'state_id' => 4, 'state_name' => 'Himachal Pradesh'],
    ['id'=>205,'city_name'=>'Solan', 1'state_id' => 4, 'state_name' => 'Himachal Pradesh'],
    ['id'=>206,'city_name'=>'Una', 1'state_id' => 4, 'state_name' => 'Himachal Pradesh'],
    ['id'=>207,'city_name'=>'Anantnag', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>208,'city_name'=>'Bandipora', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>209,'city_name'=>'Baramulla', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>210,'city_name'=>'Budgam', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>211,'city_name'=>'Doda', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>212,'city_name'=>'Ganderbal', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>213,'city_name'=>'Jammu', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>214,'city_name'=>'Kargil', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>215,'city_name'=>'Kathua', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>216,'city_name'=>'Kishtwar', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>217,'city_name'=>'Kulgam', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>218,'city_name'=>'Kupwara', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>219,'city_name'=>'Leh', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>220,'city_name'=>'Poonch', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>221,'city_name'=>'Pulwama', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>222,'city_name'=>'Rajouri', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>223,'city_name'=>'Ramban', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>224,'city_name'=>'Reasi', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>225,'city_name'=>'Samba', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>226,'city_name'=>'Shopian', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>227,'city_name'=>'Srinagar', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>228,'city_name'=>'Udhampur', 1'state_id' => 5, 'state_name' => 'Jammu and Kashmir'],
    ['id'=>229,'city_name'=>'Bokaro', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>230,'city_name'=>'Chatra', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>231,'city_name'=>'Deoghar', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>232,'city_name'=>'Dhanbad', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>233,'city_name'=>'Dumka', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>234,'city_name'=>'East Singhbhum', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>235,'city_name'=>'Garhwa', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>236,'city_name'=>'Giridih', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>237,'city_name'=>'Godda', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>238,'city_name'=>'Gumla', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>239,'city_name'=>'Hazaribag', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>240,'city_name'=>'Jamtara', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>241,'city_name'=>'Khunti', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>242,'city_name'=>'Koderma', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>243,'city_name'=>'Latehar', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>244,'city_name'=>'Lohardaga', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>245,'city_name'=>'Pakur', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>246,'city_name'=>'Palamu', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>247,'city_name'=>'Ramgarh', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>248,'city_name'=>'Ranchi', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>249,'city_name'=>'Sahibganj', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>250,'city_name'=>'Seraikela-Kharsawan', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>251,'city_name'=>'Simdega', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>252,'city_name'=>'West Singhbhum', 1'state_id' => 6, 'state_name' => 'Jharkhand'],
    ['id'=>253,'city_name'=>'Bagalkot', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>254,'city_name'=>'Bangalore Rural', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>255,'city_name'=>'Bangalore Urban', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>256,'city_name'=>'Belgaum', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>257,'city_name'=>'Bellary', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>258,'city_name'=>'Bidar', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>259,'city_name'=>'Bijapur', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>260,'city_name'=>'Chamarajanagar', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>261,'city_name'=>'Chickmagalur', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>262,'city_name'=>'Chikballapur', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>263,'city_name'=>'Chitradurga', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>264,'city_name'=>'Dakshina Kannada', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>265,'city_name'=>'Davangere', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>266,'city_name'=>'Dharwad', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>267,'city_name'=>'Gadag', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>268,'city_name'=>'Gulbarga', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>269,'city_name'=>'Hassan', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>270,'city_name'=>'Haveri', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>271,'city_name'=>'Kodagu', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>272,'city_name'=>'Kolar', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>273,'city_name'=>'Koppal', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>274,'city_name'=>'Mandya', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>275,'city_name'=>'Mysore', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>276,'city_name'=>'Raichur', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>277,'city_name'=>'Ramnagara', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>278,'city_name'=>'Shimoga', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>279,'city_name'=>'Tumkur', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>280,'city_name'=>'Udupi', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>281,'city_name'=>'Uttara Kannada (Karwar)', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>282,'city_name'=>'Yadgir', 1'state_id' => 7, 'state_name' => 'Karnataka'],
    ['id'=>283,'city_name'=>'Alappuzha', 1'state_id' => 8, 'state_name' => 'Kerala'],
    ['id'=>284,'city_name'=>'Ernakulam', 1'state_id' => 8, 'state_name' => 'Kerala'],
    ['id'=>285,'city_name'=>'Idukki', 1'state_id' => 8, 'state_name' => 'Kerala'],
    ['id'=>286,'city_name'=>'Kannur', 1'state_id' => 8, 'state_name' => 'Kerala'],
    ['id'=>287,'city_name'=>'Kasaragod', 1'state_id' => 8, 'state_name' => 'Kerala'],
    ['id'=>288,'city_name'=>'Kollam', 1'state_id' => 8, 'state_name' => 'Kerala'],
    ['id'=>289,'city_name'=>'Kottayam', 1'state_id' => 8, 'state_name' => 'Kerala'],
    ['id'=>290,'city_name'=>'Kozhikode', 1'state_id' => 8, 'state_name' => 'Kerala'],
    ['id'=>291,'city_name'=>'Malappuram', 1'state_id' => 8, 'state_name' => 'Kerala'],
    ['id'=>292,'city_name'=>'Palakkad', 1'state_id' => 8, 'state_name' => 'Kerala'],
    ['id'=>293,'city_name'=>'Pathanamthitta', 1'state_id' => 8, 'state_name' => 'Kerala'],
    ['id'=>294,'city_name'=>'Thiruvananthapuram', 1'state_id' => 8, 'state_name' => 'Kerala'],
    ['id'=>295,'city_name'=>'Thrissur', 1'state_id' => 8, 'state_name' => 'Kerala'],
    ['id'=>296,'city_name'=>'Wayanad', 1'state_id' => 8, 'state_name' => 'Kerala'],
    ['id'=>297,'city_name'=>'Lakshadweep', 1'state_id' => 9, 'state_name' => 'Lakshadweep'],
    ['id'=>298,'city_name'=>'Alirajpur', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>299,'city_name'=>'Anuppur', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>300,'city_name'=>'Ashoknagar', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>301,'city_name'=>'Balaghat', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>302,'city_name'=>'Barwani', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>303,'city_name'=>'Betul', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>304,'city_name'=>'Bhind', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>305,'city_name'=>'Bhopal', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>306,'city_name'=>'Burhanpur', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>307,'city_name'=>'Chhatarpur', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>308,'city_name'=>'Chhindwara', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>309,'city_name'=>'Damoh', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>310,'city_name'=>'Datia', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>311,'city_name'=>'Dewas', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>312,'city_name'=>'Dhar', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>313,'city_name'=>'Dindori', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>314,'city_name'=>'Guna', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>315,'city_name'=>'Gwalior', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>316,'city_name'=>'Harda', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>317,'city_name'=>'Hoshangabad', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>318,'city_name'=>'Indore', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>319,'city_name'=>'Jabalpur', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>320,'city_name'=>'Jhabua', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>321,'city_name'=>'Katni', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>322,'city_name'=>'Khandwa', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>323,'city_name'=>'Khargone', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>324,'city_name'=>'Mandla', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>325,'city_name'=>'Mandsaur', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>326,'city_name'=>'Morena', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>327,'city_name'=>'Narsinghpur', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>328,'city_name'=>'Neemuch', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>329,'city_name'=>'Panna', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>330,'city_name'=>'Raisen', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>331,'city_name'=>'Rajgarh', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>332,'city_name'=>'Ratlam', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>333,'city_name'=>'Rewa', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>334,'city_name'=>'Sagar', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>335,'city_name'=>'Satna', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>336,'city_name'=>'Sehore', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>337,'city_name'=>'Seoni', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>338,'city_name'=>'Shahdol', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>339,'city_name'=>'Shajapur', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>340,'city_name'=>'Sheopur', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>341,'city_name'=>'Shivpuri', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>342,'city_name'=>'Sidhi', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>343,'city_name'=>'Singrauli', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>344,'city_name'=>'Tikamgarh', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>345,'city_name'=>'Ujjain', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>346,'city_name'=>'Umaria', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>347,'city_name'=>'Vidisha', 2'state_id' => 0, 'state_name' => 'Madhya Pradesh'],
    ['id'=>348,'city_name'=>'Ahmednagar', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>349,'city_name'=>'Akola', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>350,'city_name'=>'Amravati', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>351,'city_name'=>'Aurangabad', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>352,'city_name'=>'Beed', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>353,'city_name'=>'Bhandara', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>354,'city_name'=>'Buldhana', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>355,'city_name'=>'Chandrapur', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>356,'city_name'=>'Dhule', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>357,'city_name'=>'Gadchiroli', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>358,'city_name'=>'Gondia', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>359,'city_name'=>'Hingoli', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>360,'city_name'=>'Jalgaon', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>361,'city_name'=>'Jalna', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>362,'city_name'=>'Kolhapur', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>363,'city_name'=>'Latur', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>364,'city_name'=>'Mumbai City', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>365,'city_name'=>'Mumbai Suburban', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>366,'city_name'=>'Nagpur', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>367,'city_name'=>'Nanded', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>368,'city_name'=>'Nandurbar', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>369,'city_name'=>'Nashik', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>370,'city_name'=>'Osmanabad', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>371,'city_name'=>'Parbhani', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>372,'city_name'=>'Pune', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>373,'city_name'=>'Raigad', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>374,'city_name'=>'Ratnagiri', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>375,'city_name'=>'Sangli', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>376,'city_name'=>'Satara', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>377,'city_name'=>'Sindhudurg', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>378,'city_name'=>'Solapur', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>379,'city_name'=>'Thane', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>380,'city_name'=>'Wardha', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>381,'city_name'=>'Washim', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>382,'city_name'=>'Yavatmal', 2'state_id' => 1, 'state_name' => 'Maharashtra'],
    ['id'=>383,'city_name'=>'Bishnupur', 2'state_id' => 2, 'state_name' => 'Manipur'],
    ['id'=>384,'city_name'=>'Chandel', 2'state_id' => 2, 'state_name' => 'Manipur'],
    ['id'=>385,'city_name'=>'Churachandpur', 2'state_id' => 2, 'state_name' => 'Manipur'],
    ['id'=>386,'city_name'=>'Imphal East', 2'state_id' => 2, 'state_name' => 'Manipur'],
    ['id'=>387,'city_name'=>'Imphal West', 2'state_id' => 2, 'state_name' => 'Manipur'],
    ['id'=>388,'city_name'=>'Senapati', 2'state_id' => 2, 'state_name' => 'Manipur'],
    ['id'=>389,'city_name'=>'Tamenglong', 2'state_id' => 2, 'state_name' => 'Manipur'],
    ['id'=>390,'city_name'=>'Thoubal', 2'state_id' => 2, 'state_name' => 'Manipur'],
    ['id'=>391,'city_name'=>'Ukhrul', 2'state_id' => 2, 'state_name' => 'Manipur'],
    ['id'=>392,'city_name'=>'East Garo Hills', 2'state_id' => 3, 'state_name' => 'Meghalaya'],
    ['id'=>393,'city_name'=>'East Jaintia Hills', 2'state_id' => 3, 'state_name' => 'Meghalaya'],
    ['id'=>394,'city_name'=>'East Khasi Hills', 2'state_id' => 3, 'state_name' => 'Meghalaya'],
    ['id'=>395,'city_name'=>'North Garo Hills', 2'state_id' => 3, 'state_name' => 'Meghalaya'],
    ['id'=>396,'city_name'=>'Ri Bhoi', 2'state_id' => 3, 'state_name' => 'Meghalaya'],
    ['id'=>397,'city_name'=>'South Garo Hills', 2'state_id' => 3, 'state_name' => 'Meghalaya'],
    ['id'=>398,'city_name'=>'South West Garo Hills', 2'state_id' => 3, 'state_name' => 'Meghalaya'],
    ['id'=>399,'city_name'=>'South West Khasi Hills', 2'state_id' => 3, 'state_name' => 'Meghalaya'],
    ['id'=>400,'city_name'=>'West Garo Hills', 2'state_id' => 3, 'state_name' => 'Meghalaya'],
    ['id'=>401,'city_name'=>'West Jaintia Hills', 2'state_id' => 3, 'state_name' => 'Meghalaya'],
    ['id'=>402,'city_name'=>'West Khasi Hills', 2'state_id' => 3, 'state_name' => 'Meghalaya'],
    ['id'=>403,'city_name'=>'Aizawl', 2'state_id' => 4, 'state_name' => 'Mizoram'],
    ['id'=>404,'city_name'=>'Champhai', 2'state_id' => 4, 'state_name' => 'Mizoram'],
    ['id'=>405,'city_name'=>'Kolasib', 2'state_id' => 4, 'state_name' => 'Mizoram'],
    ['id'=>406,'city_name'=>'Lawngtlai', 2'state_id' => 4, 'state_name' => 'Mizoram'],
    ['id'=>407,'city_name'=>'Lunglei', 2'state_id' => 4, 'state_name' => 'Mizoram'],
    ['id'=>408,'city_name'=>'Mamit', 2'state_id' => 4, 'state_name' => 'Mizoram'],
    ['id'=>409,'city_name'=>'Saiha', 2'state_id' => 4, 'state_name' => 'Mizoram'],
    ['id'=>410,'city_name'=>'Serchhip', 2'state_id' => 4, 'state_name' => 'Mizoram'],
    ['id'=>411,'city_name'=>'Dimapur', 2'state_id' => 5, 'state_name' => 'Nagaland'],
    ['id'=>412,'city_name'=>'Kiphire', 2'state_id' => 5, 'state_name' => 'Nagaland'],
    ['id'=>413,'city_name'=>'Kohima', 2'state_id' => 5, 'state_name' => 'Nagaland'],
    ['id'=>414,'city_name'=>'Longleng', 2'state_id' => 5, 'state_name' => 'Nagaland'],
    ['id'=>415,'city_name'=>'Mokokchung', 2'state_id' => 5, 'state_name' => 'Nagaland'],
    ['id'=>416,'city_name'=>'Mon', 2'state_id' => 5, 'state_name' => 'Nagaland'],
    ['id'=>417,'city_name'=>'Peren', 2'state_id' => 5, 'state_name' => 'Nagaland'],
    ['id'=>418,'city_name'=>'Phek', 2'state_id' => 5, 'state_name' => 'Nagaland'],
    ['id'=>419,'city_name'=>'Tuensang', 2'state_id' => 5, 'state_name' => 'Nagaland'],
    ['id'=>420,'city_name'=>'Wokha', 2'state_id' => 5, 'state_name' => 'Nagaland'],
    ['id'=>421,'city_name'=>'Zunheboto', 2'state_id' => 5, 'state_name' => 'Nagaland'],
    ['id'=>422,'city_name'=>'Angul', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>423,'city_name'=>'Balangir', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>424,'city_name'=>'Balasore', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>425,'city_name'=>'Bargarh', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>426,'city_name'=>'Bhadrak', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>427,'city_name'=>'Boudh', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>428,'city_name'=>'Cuttack', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>429,'city_name'=>'Deogarh', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>430,'city_name'=>'Dhenkanal', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>431,'city_name'=>'Gajapati', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>432,'city_name'=>'Ganjam', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>433,'city_name'=>'Jagatsinghapur', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>434,'city_name'=>'Jajpur', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>435,'city_name'=>'Jharsuguda', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>436,'city_name'=>'Kalahandi', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>437,'city_name'=>'Kandhamal', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>438,'city_name'=>'Kendrapara', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>439,'city_name'=>'Kendujhar (Keonjhar)', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>440,'city_name'=>'Khordha', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>441,'city_name'=>'Koraput', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>442,'city_name'=>'Malkangiri', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>443,'city_name'=>'Mayurbhanj', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>444,'city_name'=>'Nabarangpur', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>445,'city_name'=>'Nayagarh', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>446,'city_name'=>'Nuapada', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>447,'city_name'=>'Puri', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>448,'city_name'=>'Rayagada', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>449,'city_name'=>'Sambalpur', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>450,'city_name'=>'Sonepur', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>451,'city_name'=>'Sundargarh', 2'state_id' => 6, 'state_name' => 'Odisha'],
    ['id'=>452,'city_name'=>'Karaikal', 2'state_id' => 7, 'state_name' => 'Puducherry'],
    ['id'=>453,'city_name'=>'Mahe', 2'state_id' => 7, 'state_name' => 'Puducherry'],
    ['id'=>454,'city_name'=>'Pondicherry', 2'state_id' => 7, 'state_name' => 'Puducherry'],
    ['id'=>455,'city_name'=>'Yanam', 2'state_id' => 7, 'state_name' => 'Puducherry'],
    ['id'=>456,'city_name'=>'Amritsar', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>457,'city_name'=>'Barnala', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>458,'city_name'=>'Bathinda', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>459,'city_name'=>'Faridkot', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>460,'city_name'=>'Fatehgarh Sahib', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>461,'city_name'=>'Fazilka', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>462,'city_name'=>'Ferozepur', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>463,'city_name'=>'Gurdaspur', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>464,'city_name'=>'Hoshiarpur', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>465,'city_name'=>'Jalandhar', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>466,'city_name'=>'Kapurthala', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>467,'city_name'=>'Ludhiana', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>468,'city_name'=>'Mansa', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>469,'city_name'=>'Moga', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>470,'city_name'=>'Muktsar', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>471,'city_name'=>'Nawanshahr', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>472,'city_name'=>'Pathankot', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>473,'city_name'=>'Patiala', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>474,'city_name'=>'Rupnagar', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>475,'city_name'=>'Sangrur', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>476,'city_name'=>'SAS Nagar (Mohali)', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>477,'city_name'=>'Tarn Taran', 2'state_id' => 8, 'state_name' => 'Punjab'],
    ['id'=>478,'city_name'=>'test', 'state_id' => 1, 'state_name' => 'Rajasthan'],
    ['id'=>479,'city_name'=>'Alwar', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>480,'city_name'=>'Banswara', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>481,'city_name'=>'Baran', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>482,'city_name'=>'Barmer', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>483,'city_name'=>'Bharatpur', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>484,'city_name'=>'Bhilwara', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>485,'city_name'=>'Bikaner', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>486,'city_name'=>'Bundi', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>487,'city_name'=>'Chittorgarh', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>488,'city_name'=>'Churu', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>489,'city_name'=>'Dausa', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>490,'city_name'=>'Dholpur', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>491,'city_name'=>'Dungarpur', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>492,'city_name'=>'Hanumangarh', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>493,'city_name'=>'Jaipur', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>494,'city_name'=>'Jaisalmer', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>495,'city_name'=>'Jalore', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>496,'city_name'=>'Jhalawar', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>497,'city_name'=>'Jhunjhunu', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>498,'city_name'=>'Jodhpur', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>499,'city_name'=>'Karauli', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>500,'city_name'=>'Kota', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>501,'city_name'=>'Nagaur', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>502,'city_name'=>'Pali', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>503,'city_name'=>'Pratapgarh', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>504,'city_name'=>'Rajsamand', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>505,'city_name'=>'Sawai Madhopur', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>506,'city_name'=>'Sikar', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>507,'city_name'=>'Sirohi', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>508,'city_name'=>'Sri Ganganagar', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>509,'city_name'=>'Tonk', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>510,'city_name'=>'Udaipur', 2'state_id' => 9, 'state_name' => 'Rajasthan'],
    ['id'=>511,'city_name'=>'East Sikkim', 3'state_id' => 0, 'state_name' => 'Sikkim'],
    ['id'=>512,'city_name'=>'North Sikkim', 3'state_id' => 0, 'state_name' => 'Sikkim'],
    ['id'=>513,'city_name'=>'South Sikkim', 3'state_id' => 0, 'state_name' => 'Sikkim'],
    ['id'=>514,'city_name'=>'West Sikkim', 3'state_id' => 0, 'state_name' => 'Sikkim'],
    ['id'=>515,'city_name'=>'Ariyalur', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>516,'city_name'=>'Chennai', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>517,'city_name'=>'Coimbatore', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>518,'city_name'=>'Cuddalore', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>519,'city_name'=>'Dharmapuri', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>520,'city_name'=>'Dindigul', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>521,'city_name'=>'Erode', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>522,'city_name'=>'Kanchipuram', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>523,'city_name'=>'Kanyakumari', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>524,'city_name'=>'Karur', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>525,'city_name'=>'Krishnagiri', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>526,'city_name'=>'Madurai', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>527,'city_name'=>'Nagapattinam', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>528,'city_name'=>'Namakkal', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>529,'city_name'=>'Nilgiris', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>530,'city_name'=>'Perambalur', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>531,'city_name'=>'Pudukkottai', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>532,'city_name'=>'Ramanathapuram', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>533,'city_name'=>'Salem', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>534,'city_name'=>'Sivaganga', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>535,'city_name'=>'Thanjavur', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>536,'city_name'=>'Theni', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>537,'city_name'=>'Thoothukudi (Tuticorin)', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>538,'city_name'=>'Tiruchirappalli', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>539,'city_name'=>'Tirunelveli', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>540,'city_name'=>'Tiruppur', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>541,'city_name'=>'Tiruvallur', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>542,'city_name'=>'Tiruvannamalai', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>543,'city_name'=>'Tiruvarur', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>544,'city_name'=>'Vellore', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>545,'city_name'=>'Viluppuram', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>546,'city_name'=>'Virudhunagar', 3'state_id' => 1, 'state_name' => 'Tamil Nadu'],
    ['id'=>547,'city_name'=>'Adilabad', 3'state_id' => 2, 'state_name' => 'Telangana'],
    ['id'=>548,'city_name'=>'Hyderabad', 3'state_id' => 2, 'state_name' => 'Telangana'],
    ['id'=>549,'city_name'=>'Karimnagar', 3'state_id' => 2, 'state_name' => 'Telangana'],
    ['id'=>550,'city_name'=>'Khammam', 3'state_id' => 2, 'state_name' => 'Telangana'],
    ['id'=>551,'city_name'=>'Mahabubnagar', 3'state_id' => 2, 'state_name' => 'Telangana'],
    ['id'=>552,'city_name'=>'Medak', 3'state_id' => 2, 'state_name' => 'Telangana'],
    ['id'=>553,'city_name'=>'Nalgonda', 3'state_id' => 2, 'state_name' => 'Telangana'],
    ['id'=>554,'city_name'=>'Nizamabad', 3'state_id' => 2, 'state_name' => 'Telangana'],
    ['id'=>555,'city_name'=>'Rangareddy', 3'state_id' => 2, 'state_name' => 'Telangana'],
    ['id'=>556,'city_name'=>'Warangal', 3'state_id' => 2, 'state_name' => 'Telangana'],
    ['id'=>557,'city_name'=>'Dhalai', 3'state_id' => 3, 'state_name' => 'Tripura'],
    ['id'=>558,'city_name'=>'Gomati', 3'state_id' => 3, 'state_name' => 'Tripura'],
    ['id'=>559,'city_name'=>'Khowai', 3'state_id' => 3, 'state_name' => 'Tripura'],
    ['id'=>560,'city_name'=>'North Tripura', 3'state_id' => 3, 'state_name' => 'Tripura'],
    ['id'=>561,'city_name'=>'Sepahijala', 3'state_id' => 3, 'state_name' => 'Tripura'],
    ['id'=>562,'city_name'=>'South Tripura', 3'state_id' => 3, 'state_name' => 'Tripura'],
    ['id'=>563,'city_name'=>'Unakoti', 3'state_id' => 3, 'state_name' => 'Tripura'],
    ['id'=>564,'city_name'=>'West Tripura', 3'state_id' => 3, 'state_name' => 'Tripura'],
    ['id'=>565,'city_name'=>'Agra', 3'state_id' => 4, 'state_name' => 'Agra'],
    ['id'=>566,'city_name'=>'Aligarh', 3'state_id' => 4, 'state_name' => 'Aligarh'],
    ['id'=>567,'city_name'=>'Prayagraj', 3'state_id' => 4, 'state_name' => 'PRAYAGRAJ'],
    ['id'=>568,'city_name'=>'Ambedkar Nagar', 3'state_id' => 4, 'state_name' => 'AYODHYA'],
    ['id'=>569,'city_name'=>'Auraiya', 3'state_id' => 4, 'state_name' => 'Kanpur'],
    ['id'=>570,'city_name'=>'Azamgarh', 3'state_id' => 4, 'state_name' => 'Azamgarh'],
    ['id'=>571,'city_name'=>'Baghpat', 3'state_id' => 4, 'state_name' => 'Meerut'],
    ['id'=>572,'city_name'=>'Bahraich', 3'state_id' => 4, 'state_name' => 'Devipatan'],
    ['id'=>573,'city_name'=>'Ballia', 3'state_id' => 4, 'state_name' => 'Azamgarh'],
    ['id'=>574,'city_name'=>'Balrampur', 3'state_id' => 4, 'state_name' => 'Devipatan'],
    ['id'=>575,'city_name'=>'Banda', 3'state_id' => 4, 'state_name' => 'Chitrakoot'],
    ['id'=>576,'city_name'=>'Barabanki', 3'state_id' => 4, 'state_name' => 'AYODHYA'],
    ['id'=>577,'city_name'=>'Bareilly', 3'state_id' => 4, 'state_name' => 'Bareilly'],
    ['id'=>578,'city_name'=>'Basti', 3'state_id' => 4, 'state_name' => 'Basti'],
    ['id'=>579,'city_name'=>'Sambhal', 3'state_id' => 4, 'state_name' => 'Moradabad'],
    ['id'=>580,'city_name'=>'Bijnor', 3'state_id' => 4, 'state_name' => 'Moradabad'],
    ['id'=>581,'city_name'=>'Budaun', 3'state_id' => 4, 'state_name' => 'Bareilly'],
    ['id'=>582,'city_name'=>'Bulandshahr', 3'state_id' => 4, 'state_name' => 'Meerut'],
    ['id'=>583,'city_name'=>'Chandauli', 3'state_id' => 4, 'state_name' => 'Varanasi'],
    ['id'=>584,'city_name'=>'Amethi', 3'state_id' => 4, 'state_name' => 'AYODHYA'],
    ['id'=>585,'city_name'=>'Chitrakoot', 3'state_id' => 4, 'state_name' => 'Chitrakoot'],
    ['id'=>586,'city_name'=>'Deoria', 3'state_id' => 4, 'state_name' => 'Gorakhpur'],
    ['id'=>587,'city_name'=>'Etah', 3'state_id' => 4, 'state_name' => 'Aligarh'],
    ['id'=>588,'city_name'=>'Etawah', 3'state_id' => 4, 'state_name' => 'Kanpur'],
    ['id'=>589,'city_name'=>'Ayodhya', 3'state_id' => 4, 'state_name' => 'AYODHYA'],
    ['id'=>590,'city_name'=>'Farrukhabad', 3'state_id' => 4, 'state_name' => 'Kanpur'],
    ['id'=>591,'city_name'=>'Fatehpur', 3'state_id' => 4, 'state_name' => 'PRAYAGRAJ'],
    ['id'=>592,'city_name'=>'Firozabad', 3'state_id' => 4, 'state_name' => 'Agra'],
    ['id'=>593,'city_name'=>'Gautam Buddha Nagar', 3'state_id' => 4, 'state_name' => 'Meerut'],
    ['id'=>594,'city_name'=>'Ghaziabad', 3'state_id' => 4, 'state_name' => 'Meerut'],
    ['id'=>595,'city_name'=>'Ghazipur', 3'state_id' => 4, 'state_name' => 'Varanasi'],
    ['id'=>596,'city_name'=>'Gonda', 3'state_id' => 4, 'state_name' => 'Devipatan'],
    ['id'=>597,'city_name'=>'Gorakhpur', 3'state_id' => 4, 'state_name' => 'Gorakhpur'],
    ['id'=>598,'city_name'=>'Hamirpur', 3'state_id' => 4, 'state_name' => 'Chitrakoot'],
    ['id'=>599,'city_name'=>'Hardoi', 3'state_id' => 4, 'state_name' => 'Lucknow'],
    ['id'=>600,'city_name'=>'Hathras', 3'state_id' => 4, 'state_name' => 'Aligarh'],
    ['id'=>601,'city_name'=>'Jalaun', 3'state_id' => 4, 'state_name' => 'Jhansi'],
    ['id'=>602,'city_name'=>'Jaunpur', 3'state_id' => 4, 'state_name' => 'Varanasi'],
    ['id'=>603,'city_name'=>'Jhansi', 3'state_id' => 4, 'state_name' => 'Jhansi'],
    ['id'=>604,'city_name'=>'Amroha', 3'state_id' => 4, 'state_name' => 'Moradabad'],
    ['id'=>605,'city_name'=>'Kannauj', 3'state_id' => 4, 'state_name' => 'Kanpur'],
    ['id'=>606,'city_name'=>'Kanpur Dehat', 3'state_id' => 4, 'state_name' => 'Kanpur'],
    ['id'=>607,'city_name'=>'Kanpur Nagar', 3'state_id' => 4, 'state_name' => 'Kanpur'],
    ['id'=>608,'city_name'=>'Kasganj', 3'state_id' => 4, 'state_name' => 'Aligarh'],
    ['id'=>609,'city_name'=>'Kaushambi', 3'state_id' => 4, 'state_name' => 'PRAYAGRAJ'],
    ['id'=>610,'city_name'=>'Kushinagar', 3'state_id' => 4, 'state_name' => 'Gorakhpur'],
    ['id'=>611,'city_name'=>'Lakhimpur Kheri', 3'state_id' => 4, 'state_name' => 'Lucknow'],
    ['id'=>612,'city_name'=>'Lalitpur', 3'state_id' => 4, 'state_name' => 'Jhansi'],
    ['id'=>613,'city_name'=>'Lucknow', 3'state_id' => 4, 'state_name' => 'Lucknow'],
    ['id'=>614,'city_name'=>'Maharajganj', 3'state_id' => 4, 'state_name' => 'Gorakhpur'],
    ['id'=>615,'city_name'=>'Mahoba', 3'state_id' => 4, 'state_name' => 'Chitrakoot'],
    ['id'=>616,'city_name'=>'Mainpuri', 3'state_id' => 4, 'state_name' => 'Agra'],
    ['id'=>617,'city_name'=>'Mathura', 3'state_id' => 4, 'state_name' => 'Agra'],
    ['id'=>618,'city_name'=>'Mau', 3'state_id' => 4, 'state_name' => 'Azamgarh'],
    ['id'=>619,'city_name'=>'Meerut', 3'state_id' => 4, 'state_name' => 'Meerut'],
    ['id'=>620,'city_name'=>'Mirzapur', 3'state_id' => 4, 'state_name' => 'Mirzapur'],
    ['id'=>621,'city_name'=>'Moradabad', 3'state_id' => 4, 'state_name' => 'Moradabad'],
    ['id'=>622,'city_name'=>'Muzaffarnagar', 3'state_id' => 4, 'state_name' => 'Saharanpur'],
    ['id'=>623,'city_name'=>'Hapur', 3'state_id' => 4, 'state_name' => 'Meerut'],
    ['id'=>624,'city_name'=>'Pilibhit', 3'state_id' => 4, 'state_name' => 'Bareilly'],
    ['id'=>625,'city_name'=>'Shamli', 3'state_id' => 4, 'state_name' => 'Saharanpur'],
    ['id'=>626,'city_name'=>'Pratapgarh', 3'state_id' => 4, 'state_name' => 'PRAYAGRAJ'],
    ['id'=>627,'city_name'=>'Rae Bareli', 3'state_id' => 4, 'state_name' => 'Lucknow'],
    ['id'=>628,'city_name'=>'Rampur', 3'state_id' => 4, 'state_name' => 'Moradabad'],
    ['id'=>629,'city_name'=>'Saharanpur', 3'state_id' => 4, 'state_name' => 'Saharanpur'],
    ['id'=>630,'city_name'=>'Sant Kabir Nagar', 3'state_id' => 4, 'state_name' => 'Basti'],
    ['id'=>631,'city_name'=>'Bhadohi', 3'state_id' => 4, 'state_name' => 'Mirzapur'],
    ['id'=>632,'city_name'=>'Shahjahanpur', 3'state_id' => 4, 'state_name' => 'Bareilly'],
    ['id'=>633,'city_name'=>'Shravasti', 3'state_id' => 4, 'state_name' => 'Devipatan'],
    ['id'=>634,'city_name'=>'Siddharth Nagar', 3'state_id' => 4, 'state_name' => 'Basti'],
    ['id'=>635,'city_name'=>'Sitapur', 3'state_id' => 4, 'state_name' => 'Lucknow'],
    ['id'=>636,'city_name'=>'Sonbhadra', 3'state_id' => 4, 'state_name' => 'Mirzapur'],
    ['id'=>637,'city_name'=>'Sultanpur', 3'state_id' => 4, 'state_name' => 'AYODHYA'],
    ['id'=>638,'city_name'=>'Unnao', 3'state_id' => 4, 'state_name' => 'Lucknow'],
    ['id'=>639,'city_name'=>'Varanasi', 3'state_id' => 4, 'state_name' => 'Varanasi'],
    ['id'=>640,'city_name'=>'Almora', 3'state_id' => 5, 'state_name' => 'Uttarakhand'],
    ['id'=>641,'city_name'=>'Bageshwar', 3'state_id' => 5, 'state_name' => 'Uttarakhand'],
    ['id'=>642,'city_name'=>'Chamoli', 3'state_id' => 5, 'state_name' => 'Uttarakhand'],
    ['id'=>643,'city_name'=>'Champawat', 3'state_id' => 5, 'state_name' => 'Uttarakhand'],
    ['id'=>644,'city_name'=>'Dehradun', 3'state_id' => 5, 'state_name' => 'Uttarakhand'],
    ['id'=>645,'city_name'=>'Haridwar', 3'state_id' => 5, 'state_name' => 'Uttarakhand'],
    ['id'=>646,'city_name'=>'Nainital', 3'state_id' => 5, 'state_name' => 'Uttarakhand'],
    ['id'=>647,'city_name'=>'Pauri Garhwal', 3'state_id' => 5, 'state_name' => 'Uttarakhand'],
    ['id'=>648,'city_name'=>'Pithoragarh', 3'state_id' => 5, 'state_name' => 'Uttarakhand'],
    ['id'=>649,'city_name'=>'Rudraprayag', 3'state_id' => 5, 'state_name' => 'Uttarakhand'],
    ['id'=>650,'city_name'=>'Tehri Garhwal', 3'state_id' => 5, 'state_name' => 'Uttarakhand'],
    ['id'=>651,'city_name'=>'Udham Singh Nagar', 3'state_id' => 5, 'state_name' => 'Uttarakhand'],
    ['id'=>652,'city_name'=>'Uttarkashi', 3'state_id' => 5, 'state_name' => 'Uttarakhand'],
    ['id'=>653,'city_name'=>'Bankura', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>654,'city_name'=>'Birbhum', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>655,'city_name'=>'Burdwan (Bardhaman)', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>656,'city_name'=>'Cooch Behar', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>657,'city_name'=>'Dakshin Dinajpur (South Dinajpur)', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>658,'city_name'=>'Darjeeling', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>659,'city_name'=>'Hooghly', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>660,'city_name'=>'Howrah', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>661,'city_name'=>'Jalpaiguri', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>662,'city_name'=>'Kolkata', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>663,'city_name'=>'Malda', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>664,'city_name'=>'Murshidabad', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>665,'city_name'=>'Nadia', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>666,'city_name'=>'North 24 Parganas', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>667,'city_name'=>'Paschim Medinipur (West Medinipur)', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>668,'city_name'=>'Purba Medinipur (East Medinipur)', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>669,'city_name'=>'Purulia', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>670,'city_name'=>'South 24 Parganas', 3'state_id' => 6, 'state_name' => 'West Bengal'],
    ['id'=>671,'city_name'=>'Uttar Dinajpur (North Dinajpur)', 'state_id' => 36, 'state_name' => 'West Bengal']];

        DB::table('states')->insert($states);
        DB::table('cities')->insert($cities);
    }
}
